"""Small data-access layer shared by all routers.

Wraps the hybrid document pattern (see models.py) with simple document verbs
so the routers read almost like the legacy (v1) routes they replaced:

    v1  db.get('chemicals').value()          → all_docs(db, Chemical)
    v1  .find({chemical_id: id}).value()     → find_row(db, Chemical, 'chemical_id', id)
    v1  .push(doc).write()                   → insert_doc(db, Chemical, doc)
    v1  .assign(doc).write()                 → replace_doc(row, doc)
"""

import re
from typing import Any, Optional, Type

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from .database import Base

# The column each model uses as its business key, mirrored from doc on write.
_KEY_FIELD = {
    "chemicals": "chemical_id",
    "samples": "sample_id",
    "screening": "chemical_id",
    "toxicology": "chemical_id",
}


_CHEMICAL_ID_RE = re.compile(r"^CHEM-(\d+)$")


def next_chemical_id(db: Session, offset: int = 0) -> str:
    """The next sequential chemical identifier, `CHEM-000001` and upward.

    The chemical's own identifier is generated by this application, not taken
    from a file. An uploaded `DTX_ID` is a *different* identifier belonging to
    an external system; storing it as the primary key made the two look like
    one thing and left compounds with no DTX_ID carrying an invented one.

    `offset` lets a caller allocate several ids in a batch without writing each
    one first.
    """
    highest = 0
    for row in db.scalars(select(model_chemical().chemical_id)):
        match = _CHEMICAL_ID_RE.match(row or "")
        if match:
            highest = max(highest, int(match.group(1)))
    return f"CHEM-{highest + 1 + offset:06d}"


def model_chemical():
    """Imported lazily to keep this module free of model imports at load time."""
    from .models import Chemical

    return Chemical


def all_rows(db: Session, model: Type[Base]) -> list:
    """All rows in original array order (insertion order via `seq`)."""
    return list(db.scalars(select(model).order_by(model.seq)))


def all_docs(db: Session, model: Type[Base]) -> list[dict[str, Any]]:
    """All record documents in insertion order — the v1 `.value()` equivalent."""
    return [row.doc for row in all_rows(db, model)]


def find_row(db: Session, model: Type[Base], field: str, value: Any):
    """First row whose extracted column `field` equals `value` (or None)."""
    return db.scalars(select(model).where(getattr(model, field) == value)).first()


def _next_seq(db: Session, model: Type[Base]) -> int:
    current = db.scalar(select(func.max(model.seq)))
    return (current or 0) + 1


def _sync_columns(row, doc: dict[str, Any]) -> None:
    """Copy the indexed lookup values out of the document into real columns."""
    key = _KEY_FIELD[row.__tablename__]
    setattr(row, key, doc.get(key))
    row.created_at = doc.get("created_at")


def insert_doc(db: Session, model: Type[Base], doc: dict[str, Any]) -> None:
    """Insert a new record document (v1 `.push(...).write()`)."""
    row = model(id=doc["id"], seq=_next_seq(db, model), doc=doc)
    _sync_columns(row, doc)
    db.add(row)
    db.commit()


def insert_docs_bulk(db: Session, model: Type[Base], docs: list[dict[str, Any]]) -> int:
    """Insert many documents in one transaction; returns how many were added.

    `insert_doc` is fine for a handful of records but issues a `SELECT max(seq)`
    **and a commit per row** — at 49,000 rows that is 49,000 flushes to disk and
    takes hours on SQLite. This computes `seq` once, builds every row in memory,
    and commits a single time.

    Behaviour is otherwise identical to calling `insert_doc` in a loop, so the
    stored shape (and therefore the API contract) is unchanged.
    """
    if not docs:
        return 0
    seq = _next_seq(db, model)
    rows = []
    for offset, doc in enumerate(docs):
        row = model(id=doc["id"], seq=seq + offset, doc=doc)
        _sync_columns(row, doc)
        rows.append(row)
    db.add_all(rows)
    db.commit()
    return len(rows)


def replace_doc(db: Session, row, doc: dict[str, Any]) -> None:
    """Replace a row's document (v1 `.assign(...).write()`).

    A NEW dict must be assigned (not mutated in place) so SQLAlchemy's
    change tracking notices the JSON column changed.
    """
    row.doc = doc
    _sync_columns(row, doc)
    db.commit()


def delete_row(db: Session, row) -> None:
    db.delete(row)
    db.commit()


def clear_all(db: Session, model: Type[Base]) -> int:
    """Delete every row; returns how many were deleted (v1 `.set(col, [])`)."""
    rows = all_rows(db, model)
    for row in rows:
        db.delete(row)
    db.commit()
    return len(rows)
